{{/* Generate secrets for AI Guardian system with FreeBSD security integration */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardian.fullname" . }}-secrets
  labels:
    {{- include "guardian.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-5"
    security.guardian.io/audit: "enabled"
    security.guardian.io/rotation: "enabled"
    security.guardian.io/tpm-verified: "true"
    security.guardian.io/hsm-protected: "true"
    security.guardian.io/freebsd-compatible: "true"
    security.guardian.io/capsicum-enabled: {{ .Values.global.security.capsicum.enabled | quote }}
    security.guardian.io/secure-level: {{ .Values.global.freebsd.sysctls.kern\.securelevel | quote }}
type: Opaque
data:
  # HSM Integration Secrets
  hsm_auth: {{ required "HSM authentication credentials are required" .Values.global.security.hsm.auth | b64enc | quote }}
  hsm_config: {{ required "HSM configuration is required" .Values.global.security.hsm.config | b64enc | quote }}
  hsm_slot_id: {{ .Values.global.security.hsm.slotId | default "0" | b64enc | quote }}
  hsm_pin: {{ required "HSM PIN is required" .Values.global.security.hsm.pin | b64enc | quote }}

  # TPM Integration Secrets
  tpm_auth: {{ required "TPM authentication credentials are required" .Values.global.security.tpm.auth | b64enc | quote }}
  tpm_pcr: {{ required "TPM PCR measurements are required" .Values.global.security.tpm.pcr | b64enc | quote }}
  tpm_device_path: {{ .Values.global.security.tpm.devicePath | default "/dev/tpm0" | b64enc | quote }}
  tpm_owner_auth: {{ required "TPM owner authentication is required" .Values.global.security.tpm.ownerAuth | b64enc | quote }}

  # Temporal.io Credentials
  temporal_auth: {{ required "Temporal.io authentication credentials are required" .Values.global.security.temporal.auth | b64enc | quote }}
  temporal_namespace: {{ required "Temporal.io namespace is required" .Values.global.security.temporal.namespace | b64enc | quote }}
  temporal_tls_cert: {{ required "Temporal.io TLS certificate is required" .Values.global.security.temporal.tlsCert | b64enc | quote }}
  temporal_tls_key: {{ required "Temporal.io TLS key is required" .Values.global.security.temporal.tlsKey | b64enc | quote }}

  # System-wide Encryption Keys
  system_keys: {{ required "System encryption keys are required" .Values.global.security.encryption.keys | b64enc | quote }}
  rotation_metadata: {{ required "Key rotation metadata is required" .Values.global.security.encryption.rotation | b64enc | quote }}
  master_key_id: {{ required "Master key ID is required" .Values.global.security.encryption.masterKeyId | b64enc | quote }}
  key_encryption_key: {{ required "Key encryption key is required" .Values.global.security.encryption.keyEncryptionKey | b64enc | quote }}

  # FreeBSD Security Integration
  capsicum_capabilities: {{ .Values.global.security.capsicum.capabilities | toJson | b64enc | quote }}
  securelevel_config: {{ .Values.global.freebsd.sysctls | toJson | b64enc | quote }}
  kernel_modules: {{ .Values.global.freebsd.kernelModules | toJson | b64enc | quote }}

  # Audit and Compliance
  audit_signing_key: {{ required "Audit signing key is required" .Values.global.security.audit.signingKey | b64enc | quote }}
  audit_public_key: {{ required "Audit public key is required" .Values.global.security.audit.publicKey | b64enc | quote }}
  compliance_policy: {{ required "Compliance policy is required" .Values.global.security.compliance.policy | b64enc | quote }}

---
# Separate secret for rotating keys
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardian.fullname" . }}-rotating-keys
  labels:
    {{- include "guardian.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-4"
    security.guardian.io/rotation-schedule: "168h"  # 7 days
    security.guardian.io/last-rotation: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }}
type: Opaque
data:
  active_keys: {{ required "Active encryption keys are required" .Values.global.security.encryption.activeKeys | b64enc | quote }}
  standby_keys: {{ required "Standby encryption keys are required" .Values.global.security.encryption.standbyKeys | b64enc | quote }}
  rotation_schedule: {{ .Values.global.security.encryption.rotationSchedule | default "168h" | b64enc | quote }}