apiVersion: v2
name: guardian
description: AI Guardian autonomous security and management system for FreeBSD-based gaming console platform, providing real-time threat detection, ML-based analysis, and automated response capabilities

type: application
version: 1.0.0
appVersion: 1.0.0

keywords:
  - security
  - gaming
  - freebsd
  - machine-learning
  - autonomous
  - threat-detection
  - zero-trust
  - container-security
  - gaming-console

home: https://github.com/guardian/guardian
sources:
  - https://github.com/guardian/guardian

maintainers:
  - name: Guardian Security Team
    email: security@guardian.io
    url: https://guardian.io/security

annotations:
  platform/freebsd: "13.2"
  security/signed: "true"
  deployment/phased: "true"
  runtime/jail-compatible: "true"
  guardian.io/security-contact: security@guardian.io
  guardian.io/compliance-level: gaming-console-certified

dependencies:
  - name: temporal
    version: 1.20.0
    repository: https://helm.temporal.io
    condition: temporal.enabled
    tags:
      - workflow-engine

  - name: prometheus
    version: 15.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
    tags:
      - monitoring

  - name: grafana
    version: 6.50.0
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
    tags:
      - visualization

engine: ">=3.12.0"