# Kubernetes Secrets configuration for AI Guardian system
# Version: v1
# Rotation schedule: Monthly on the 1st (0 0 1 * *)
# Encryption: AES-256-GCM
# Namespace: guardian-system

apiVersion: v1
kind: Secret
metadata:
  name: guardian-secrets
  namespace: guardian-system
  annotations:
    kubernetes.io/rotation-schedule: "0 0 1 * *"
    guardian.io/rotation-period: "30d"
    guardian.io/encryption: "aes-256-gcm"
    guardian.io/audit-logging: "enabled"
type: Opaque
data:
  tls.crt: ${TLS_CERTIFICATE}
  tls.key: ${TLS_PRIVATE_KEY}
  encryption-key: ${ENCRYPTION_KEY}
  hsm-credentials: ${HSM_CREDENTIALS}
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-secrets
  namespace: guardian-system
  annotations:
    kubernetes.io/rotation-schedule: "0 0 1 * *"
    guardian.io/rotation-period: "90d"
    guardian.io/encryption: "aes-256-gcm"
    guardian.io/audit-logging: "enabled"
type: kubernetes.io/tls
data:
  client.crt: ${TEMPORAL_CLIENT_CERT}
  client.key: ${TEMPORAL_CLIENT_KEY}
  ca.crt: ${TEMPORAL_CA_CERT}
---
apiVersion: v1
kind: Secret
metadata:
  name: ml-model-secrets
  namespace: guardian-system
  annotations:
    kubernetes.io/rotation-schedule: "0 0 1 * *"
    guardian.io/rotation-period: "60d"
    guardian.io/encryption: "aes-256-gcm"
    guardian.io/audit-logging: "enabled"
type: Opaque
data:
  model-encryption-key: ${MODEL_ENCRYPTION_KEY}
  model-signing-key: ${MODEL_SIGNING_KEY}
---
# RBAC configuration for secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: guardian-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["guardian-secrets", "temporal-secrets", "ml-model-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: guardian-system
subjects:
- kind: ServiceAccount
  name: guardian-service
  namespace: guardian-system
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io