name: FreeBSD CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/freebsd/**'
      - '.github/workflows/freebsd-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/freebsd/**'
      - '.github/workflows/freebsd-ci.yml'

env:
  FREEBSD_VERSION: '13.0'
  GUARDIAN_BUILD_FLAGS: '-DGUARDIAN_DEBUG -O2 -DSECURITY_ENHANCED'
  TEST_REPORT_DIR: '/var/log/guardian/test_reports'
  RESOURCE_LIMITS: 'cpu=80%,memory=4GB'
  SECURITY_BASELINE: '/etc/guardian/security_baseline.json'

jobs:
  build:
    name: Build FreeBSD Components
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup FreeBSD environment
        uses: actions/setup-freebsd@v1
        with:
          freebsd-version: ${{ env.FREEBSD_VERSION }}

      - name: Initialize security baseline
        run: |
          mkdir -p /etc/guardian
          touch ${{ env.SECURITY_BASELINE }}
          chmod 600 ${{ env.SECURITY_BASELINE }}

      - name: Build kernel modules
        run: |
          cd src/freebsd/tools
          sh build_modules.sh
        env:
          KERNEL_SRC: /usr/src/sys
          BUILD_FLAGS: ${{ env.GUARDIAN_BUILD_FLAGS }}
          MAX_PARALLEL_JOBS: 4

      - name: Validate build artifacts
        run: |
          for module in guardian.ko guardian_utils.ko guardian_hardware.ko; do
            if [ ! -f "/boot/modules/${module}" ]; then
              echo "Error: Module ${module} not found"
              exit 1
            fi
            kldxref -v "/boot/modules/${module}"
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: guardian-modules
          path: |
            /boot/modules/guardian*.ko
            /var/log/guardian/build_report.json
          retention-days: 7

  test:
    name: Test FreeBSD Components
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup FreeBSD environment
        uses: actions/setup-freebsd@v1
        with:
          freebsd-version: ${{ env.FREEBSD_VERSION }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: guardian-modules
          path: /boot/modules

      - name: Run kernel tests
        run: |
          cd src/freebsd/tools
          sh run_tests.sh
        env:
          TEST_ROOT: /usr/local/tests/guardian
          TEST_TIMEOUT: 300
          MAX_RETRIES: 3

      - name: Run security tests
        run: |
          cd src/freebsd/tools
          sh security_check.sh
        env:
          GUARDIAN_SECURITY_CHECKS: "capsicum mac geli jail kernel audit resource"
          GUARDIAN_MIN_SECURITY_LEVEL: 2

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            ${{ env.TEST_REPORT_DIR }}/*.html
            ${{ env.TEST_REPORT_DIR }}/*.xml
            ${{ env.TEST_REPORT_DIR }}/*.json
          retention-days: 7

  security-audit:
    name: Security Audit
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup FreeBSD environment
        uses: actions/setup-freebsd@v1
        with:
          freebsd-version: ${{ env.FREEBSD_VERSION }}

      - name: Run security audit
        run: |
          cd src/freebsd/tools
          sh security_check.sh --audit-mode
        env:
          GUARDIAN_SECURITY_LEVEL: 3
          GUARDIAN_AUDIT_ENABLE: 1

      - name: Validate Capsicum configuration
        run: |
          sysctl security.capability_mode
          for pid in $(pgrep -f "guardian_"); do
            procstat -c ${pid} | grep "capability_mode"
          done

      - name: Check MAC policy compliance
        run: |
          kldstat -n mac_guardian
          diff -u /etc/mac.conf ${{ env.SECURITY_BASELINE }}

      - name: Verify GELI encryption
        run: |
          geom eli list
          geom eli status

      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: |
            /var/log/guardian/security_audit.log
            /var/log/guardian/security_check.log
          retention-days: 30